# Generated by Django 4.0.4 on 2023-02-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=250)),
                ('job_order_no', models.CharField(max_length=50)),
                ('defect_image', models.ImageField(blank=True, null=True, upload_to='defects_images/')),
                ('created_at', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
